version: "3"
services:
  node-app:
    image: node-app-image
    ports:
      - 3000:3000
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=sun291514001
      - MYSQL_DB=db_management
    ports:
      - 3306:3306
    volumes:
      - mysql-db:/data/db

volumes:
  mysql-db:
    driver: local
